## 1. Carga de datos

En esta etapa realizaremos la carga de la base de datos que será utilizada durante el desarrollo del Proyecto Integrador del Módulo 5.

El objetivo es comprobar que el archivo puede leerse correctamente y obtener una primera visión de su estructura antes de iniciar el análisis exploratorio de datos.

La estructura oficial del proyecto solicita que la base de datos se encuentre en la raíz del repositorio con el nombre `Base_de_datos.csv`.

En esta sección cargaremos el archivo y validaremos que pueda leerse correctamente desde el notebook.

In [22]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from pathlib import Path

ruta_csv = Path("../Base_de_datos.csv")

if not ruta_csv.exists():
    ruta_csv = Path("Base_de_datos.csv")

df = pd.read_csv(ruta_csv)

df.head()

,tipo_credito,fecha_prestamo,capital_prestado,plazo_meses,edad_cliente,tipo_laboral,salario_cliente,total_otros_prestamos,cuota_pactada,puntaje,...,saldo_mora,saldo_total,saldo_principal,saldo_mora_codeudor,creditos_sectorFinanciero,creditos_sectorCooperativo,creditos_sectorReal,promedio_ingresos_datacredito,tendencia_ingresos,Pago_atiempo
0,7,2024-12-21 11:31:35,3692160.0,10,42,Independiente,8000000,2500000,341296,88.768094,...,0.0,51258.0,51258.0,0.0,5,0,0,908526.0,Estable,1
1,4,2025-04-22 09:47:35,840000.0,6,60,Empleado,3000000,2000000,124876,95.227787,...,0.0,8673.0,8673.0,0.0,0,0,2,939017.0,Creciente,1
2,9,2026-01-08 12:22:40,5974028.4,10,36,Independiente,4036000,829000,529554,47.613894,...,0.0,18702.0,18702.0,0.0,3,0,0,NaN,NaN,0
3,4,2025-08-04 12:04:10,1671240.0,6,48,Empleado,1524547,498000,252420,95.227787,...,0.0,15782.0,15782.0,0.0,3,0,0,1536193.0,Creciente,1
4,9,2025-04-26 11:24:26,2781636.0,11,44,Empleado,5000000,4000000,217037,95.227787,...,0.0,204804.0,204804.0,0.0,3,0,1,933473.0,Creciente,1

Después de cargar la base, revisaremos cuántos registros y variables contiene el dataset. Esto permite tener una primera idea del tamaño de la información disponible para el análisis y modelado posterior.

In [8]:
filas, columnas = df.shape
print(f"filas: {filas}, columnas: {columnas}")

filas: 10763, columnas: 23

También revisaremos el nombre de las columnas para identificar las variables disponibles y ubicar la variable objetivo del proyecto.

In [9]:
df.columns.tolist()

['tipo_credito',
 'fecha_prestamo',
 'capital_prestado',
 'plazo_meses',
 'edad_cliente',
 'tipo_laboral',
 'salario_cliente',
 'total_otros_prestamos',
 'cuota_pactada',
 'puntaje',
 'puntaje_datacredito',
 'cant_creditosvigentes',
 'huella_consulta',
 'saldo_mora',
 'saldo_total',
 'saldo_principal',
 'saldo_mora_codeudor',
 'creditos_sectorFinanciero',
 'creditos_sectorCooperativo',
 'creditos_sectorReal',
 'promedio_ingresos_datacredito',
 'tendencia_ingresos',
 'Pago_atiempo']

## 2. Información general del dataset

Ahora que conocemos las variables con las que trabajaremos, revisaremos la estructura general de la base de datos: tipos de variables, cantidad de valores no nulos y composición inicial del DataFrame, con el fin de detectar posibles problemas antes de avanzar al análisis exploratorio.

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10763 entries, 0 to 10762
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   tipo_credito                   10763 non-null  int64
 1   fecha_prestamo                 10763 non-null  str
 2   capital_prestado               10763 non-null  float64
 3   plazo_meses                    10763 non-null  int64
 4   edad_cliente                   10763 non-null  int64
 5   tipo_laboral                   10763 non-null  str
 6   salario_cliente                10763 non-null  int64
 7   total_otros_prestamos          10763 non-null  int64
 8   cuota_pactada                  10763 non-null  int64
 9   puntaje                        10763 non-null  float64
 10  puntaje_datacredito            10757 non-null  float64
 11  cant_creditosvigentes          10763 non-null  int64
 12  huella_consulta                10763 non-null  int64
 13  saldo_mora                     10607 non-null  float64
 14  saldo_total                    10607 non-null  float64
 15  saldo_principal                10358 non-null  float64
 16  saldo_mora_codeudor            10173 non-null  float64
 17  creditos_sectorFinanciero      10763 non-null  int64
 18  creditos_sectorCooperativo     10763 non-null  int64
 19  creditos_sectorReal            10763 non-null  int64
 20  promedio_ingresos_datacredito  7833 non-null   float64
 21  tendencia_ingresos             7831 non-null   str
 22  Pago_atiempo                   10763 non-null  int64
dtypes: float64(8), int64(12), str(3)
memory usage: 2.3 MB

#### Registros nulos
Los valores nulos pueden afectar el análisis exploratorio y el entrenamiento de modelos, por lo que es necesario identificarlos desde la etapa inicial de carga de datos.

In [ ]:
nulos_df = df.isnull().sum().reset_index()
nulos_df.columns = ["columna", "nulos"]
nulos_df["porcentaje"] = (nulos_df["nulos"] / len(df) * 100).round(2)

nulos_df = nulos_df[nulos_df["nulos"] > 0].sort_values(
    by="nulos",
    ascending=False
)
nulos_df

                          columna  nulos  porcentaje
21             tendencia_ingresos   2932       27.24
20  promedio_ingresos_datacredito   2930       27.22
16            saldo_mora_codeudor    590        5.48
15                saldo_principal    405        3.76
13                     saldo_mora    156        1.45
14                    saldo_total    156        1.45
10            puntaje_datacredito      6        0.06

De acuerdo con la revisión de valores nulos echa anteriormente en "Cargar_datos.ipynb", algunas variables presentan datos faltantes en proporciones relevantes. Estas columnas deberán ser consideradas en la etapa de ingeniería de características para definir un tratamiento adecuado.

Por ahora no se modifican los valores faltantes, ya que el objetivo de este notebook es comprender el estado inicial de los datos antes de aplicar transformaciones.

#### Registros duplicados
También revisaremos si existen registros duplicados completos dentro de la base, ya que podrían alterar los resultados del análisis o sesgar el entrenamiento del modelo.

In [12]:
duplicados = df.duplicated().sum()
print(f"Registros duplicados: {duplicados}")

Registros duplicados: 0

Además, no se identificaron registros duplicados completos en la base de datos. Esto indica que, al menos a nivel de filas completas, no hay repeticiones que debnn eliminarse antes del análisis exploratorio.

## 4. Interpretación inicial

La variable objetivo `Pago_atiempo` presenta dos clases: clientes que pagaron a tiempo y clientes que no lo hicieron. 

La revisión de su distribución permite identificar si existe desbalance entre las clases, lo cual será importante en etapas posteriores del proyecto, especialmente durante el entrenamiento y evaluación

Como parte de la carga inicial, separamos las columnas según su tipo de dato. Esto permite distinguir entre variables numéricas, categóricas y de fecha, lo cual será útil para el análisis exploratorio y la ingeniería de características.

In [19]:
columnas_numericas = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
columnas_categoricas = df.select_dtypes(include=["object"]).columns.tolist()

print("Columnas numéricas:")
print(columnas_numericas)

print("\nColumnas categóricas:")
print(columnas_categoricas)

Columnas numéricas:
['tipo_credito', 'capital_prestado', 'plazo_meses', 'edad_cliente', 'salario_cliente', 'total_otros_prestamos', 'cuota_pactada', 'puntaje', 'puntaje_datacredito', 'cant_creditosvigentes', 'huella_consulta', 'saldo_mora', 'saldo_total', 'saldo_principal', 'saldo_mora_codeudor', 'creditos_sectorFinanciero', 'creditos_sectorCooperativo', 'creditos_sectorReal', 'promedio_ingresos_datacredito', 'Pago_atiempo']

Columnas categóricas:
['fecha_prestamo', 'tipo_laboral', 'tendencia_ingresos']

C:\Users\Ismael2\AppData\Local\Temp\ipykernel_21900\3686470735.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columnas_categoricas = df.select_dtypes(include=["object"]).columns.tolist()

Finalmente, se obtiene una primera descripción estadística de las variables numéricas. Esta revisión no sustituye al EDA, pero permite observar rangos, promedios y posibles valores extremos de manera preliminar.

In [20]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
tipo_credito,10763.0,5.411131e+00,2.338279e+00,4.00000,4.000000e+00,4.000000e+00,9.000000e+00,6.800000e+01
capital_prestado,10763.0,2.434315e+06,1.909643e+06,360000.00000,1.224831e+06,1.921920e+06,3.084840e+06,4.144415e+07
plazo_meses,10763.0,1.057558e+01,6.632082e+00,2.00000,6.000000e+00,1.000000e+01,1.200000e+01,9.000000e+01
edad_cliente,10763.0,4.394862e+01,1.506088e+01,19.00000,3.300000e+01,4.200000e+01,5.300000e+01,1.230000e+02
salario_cliente,10763.0,1.721643e+07,3.554767e+08,0.00000,2.000000e+06,3.000000e+06,4.875808e+06,2.200000e+10
total_otros_prestamos,10763.0,6.238870e+06,1.184183e+08,0.00000,5.000000e+05,1.000000e+06,2.000000e+06,6.787675e+09
cuota_pactada,10763.0,2.436174e+05,2.104937e+05,23944.00000,1.210415e+05,1.828630e+05,2.878335e+05,3.816752e+06
puntaje,10763.0,9.117004e+01,1.646544e+01,-38.00999,9.522779e+01,9.522779e+01,9.522779e+01,9.522779e+01
puntaje_datacredito,10757.0,7.807908e+02,1.048780e+02,-7.00000,7.570000e+02,7.910000e+02,8.250000e+02,9.990000e+02
cant_creditosvigentes,10763.0,5.726749e+00,3.977162e+00,0.00000,3.000000e+00,5.000000e+00,8.000000e+00,6.200000e+01
huella_consulta,10763.0,4.228561e+00,3.064683e+00,0.00000,2.000000e+00,4.000000e+00,6.000000e+00,2.900000e+01
saldo_mora,10607.0,7.746017e+00,2.259551e+02,0.00000,0.000000e+00,0.000000e+00,0.000000e+00,1.253400e+04
saldo_total,10607.0,4.593741e+04,1.062698e+05,0.00000,2.898000e+03,1.617800e+04,5.298200e+04,5.116066e+06
saldo_principal,10358.0,4.034617e+04,7.124244e+04,0.00000,2.690000e+03,1.444250e+04,4.763225e+04,1.562285e+06
saldo_mora_codeudor,10173.0,2.600020e-01,2.177292e+01,0.00000,0.000000e+00,0.000000e+00,0.000000e+00,2.145000e+03
creditos_sectorFinanciero,10763.0,2.779987e+00,2.748807e+00,0.00000,1.000000e+00,2.000000e+00,4.000000e+00,5.100000e+01
creditos_sectorCooperativo,10763.0,2.698132e-01,7.164708e-01,0.00000,0.000000e+00,0.000000e+00,0.000000e+00,1.300000e+01
creditos_sectorReal,10763.0,1.302704e+00,1.824430e+00,0.00000,0.000000e+00,1.000000e+00,2.000000e+00,2.500000e+01
promedio_ingresos_datacredito,7833.0,2.005157e+06,2.144116e+06,0.00000,9.251570e+05,1.204496e+06,2.231859e+06,3.810658e+07
Pago_atiempo,10763.0,9.525225e-01,2.126677e-01,0.00000,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

## 5. Conclusiones preeliminares

Con esta primera revisión identificamos las dimensiones del dataset, las columnas disponibles, los tipos de datos, la presencia de valores nulos, la ausencia de registros duplicados y la variable objetivo `Pago_atiempo`, de la cual, pudimos observar su distribución inicial, lo cual será relevante para las siguientes etapas del proyecto, especialmente en el análisis exploratorio, la ingeniería de características y la evaluación de modelos.